config/routes.rb
AvpMobile::Application.routes.draw do
  resources :reservations

  resources :lots

  resources :vehicles

  resources :users

  root :to => 'lots#control'
  
  match 'find' => 'lots#map'
  match 'pay' => 'users#pay'
  match 'account' => 'users#account'
  match 'control' => 'lots#control'
  match 'park' => 'lots#park'
  match 'retrieve' => 'lots#retrieve'
  match 'manual' => 'lots#manual'

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  attr_accessible :address, :capacity, :name, :price
  has_many :reservations
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lots }
    end
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/new
  # GET /lots/new.json
  def new
    @lot = Lot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/1/edit
  def edit
    @lot = Lot.find(params[:id])
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(params[:lot])

    respond_to do |format|
      if @lot.save
        format.html { redirect_to @lot, notice: 'Lot was successfully created.' }
        format.json { render json: @lot, status: :created, location: @lot }
      else
        format.html { render action: "new" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lots/1
  # PUT /lots/1.json
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to lots_url }
      format.json { head :no_content }
    end
  end

  def map

  end

  def park

  end

  def retrieve

  end

  def manual

  end

  def parse_response
    
  end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_for(@lot) do |f| %>
  <% if @lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% @lot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lots/control.html.erb
<div data-role="header" data-theme="a">
	<h1>AutoValetPark</h1>
	<%= link_to 'Manual', {:controller => "lots", :action => "manual"}, "class" => "ui-btn-right", "data-icon" => "gear" %>
</div>

<div data-role="fieldcontain" id="avp_logo">
	<%= image_tag('logo-twitter-500.png') %>
</div>

<div class="control_buttons">
	<%= link_to "Park", {:controller => "lots", :action => "park"}, "data-role"=> "button", 'data-theme' => 'e', :id => "park_button" %>
	<%= link_to "Retrieve",{:controller => "lots", :action => "retrieve"}, "data-role" => "button", "data-theme" => 'b', :id => "retrieve_button" %>
</div>

app/views/lots/edit.html.erb
<h1>Editing lot</h1>

<%= render 'form' %>

<%= link_to 'Show', @lot %> |
<%= link_to 'Back', lots_path %>

app/views/lots/index.html.erb
<h1>Listing lots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Capacity</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lots.each do |lot| %>
  <tr>
    <td><%= lot.name %></td>
    <td><%= lot.address %></td>
    <td><%= lot.capacity %></td>
    <td><%= lot.price %></td>
    <td><%= link_to 'Show', lot %></td>
    <td><%= link_to 'Edit', edit_lot_path(lot) %></td>
    <td><%= link_to 'Destroy', lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lot', new_lot_path %>

app/views/lots/manual.html.erb
<div data-role="header">
	<a href="#" data-icon="back" data-rel="back" class="ui-btn-left">Back</a>
    <h1>Manual Mode GUI</h1>
</div>

<p>THIS IS THE MANUAL MODE... USE WITH CAUTION</p>
<p>ADMIN ONLY!<p>

app/views/lots/map.html.erb
<input type="search" name="search_location" id="search" value="" placeholder="Search for a Parking Lot">

<div id="map_canvas" style="width:300px;height:300px;"></div>

<ul data-role="listview" id="lots_list">
    <li><a href="#">South Campus Hall</a></li>
    <li><a href="#">Student Life Centre</a></li>
    <li><a href="#">UW Plaza</a></li>
</ul>
<div data-role="footer" class="ui-bar">
    <%= link_to "Find", {:controller => "lots", :action => "map"}, "data-role" => "button", "data-icon" => "search" %>
    <%= link_to "Pay", {:controller => "users", :action => "pay"}, "data-role" => "button", "data-icon" => "home" %>
    <%= link_to "Account", {:controller => "users", :action => "account"}, "data-role" => "button", "data-icon" => "gear" %>
</div>

app/views/lots/new.html.erb
<h1>New lot</h1>

<%= render 'form' %>

<%= link_to 'Back', lots_path %>

app/views/lots/park.html.erb
<div data-role="header">
	<a href="#" data-icon="back" data-rel="back" class="ui-btn-left">Back</a>
    <h1>Park Vehicle</h1>
    <%= link_to 'Manual', {:controller => "lots", :action => "manual"}, "class" => "ui-btn-right", "data-icon" => "gear" %>
</div>

<div class='control_buttons' data-role='fieldcontain'>
	<%= select_tag "bay_number", options_for_select(1..4) %>
    <%= link_to "Park My Ride", '#', "data-theme" => "e", "data-role" => "button", :id => "car_park_button" %>
</div>
<div data-role="fieldset" id="park_result">
</div>

app/views/lots/retrieve.html.erb
<div data-role="header">
	<a href="#" data-icon="back" data-rel="back" class="ui-btn-left">Back</a>
    <h1>Park Vehicle</h1>
	<%= link_to 'Manual', {:controller => "lots", :action => "manual"}, "class" => "ui-btn-right", "data-icon" => "gear" %>
</div>

<div data-role="fieldset" class='control_buttons'>
	<%= text_field_tag 'ticket_number', nil, :placeholder => "Enter Ticket Number ..." %>
    <%= link_to 'Fetch My Ride', '#', 'data-theme' => 'e', 'data-role' => 'button', :id => 'car_retrieve_button' %>
</div>

<div data-role="fieldset" id="retrieve_result">
</div>
<!--% end %-->

app/views/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lot.name %>
</p>

<p>
  <b>Address:</b>
  <%= @lot.address %>
</p>

<p>
  <b>Capacity:</b>
  <%= @lot.capacity %>
</p>

<p>
  <b>Price:</b>
  <%= @lot.price %>
</p>


<%= link_to 'Edit', edit_lot_path(@lot) %> |
<%= link_to 'Back', lots_path %>